# Generated by Django 5.1 on 2024-09-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0002_authuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(default="photo/default.png", upload_to="photo/"),
        ),
    ]
