# Generated by Django 5.1 on 2024-10-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0007_alter_authuser_photo_alter_candidate_resume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateeducation",
            name="Percentage",
        ),
    ]
