# Generated by Django 5.1 on 2024-10-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0009_alter_candidateeducation_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateeducation",
            old_name="end_date",
            new_name="end_year",
        ),
        migrations.RenameField(
            model_name="candidateeducation",
            old_name="start_date",
            new_name="start_year",
        ),
    ]
