# Generated by Django 5.1 on 2024-10-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0011_alter_candidate_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="end_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="start_year",
            field=models.PositiveIntegerField(),
        ),
    ]
