# Generated by Django 5.1 on 2024-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0012_alter_candidateeducation_end_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="Feild_of_study",
            field=models.CharField(max_length=200),
        ),
    ]
