# Generated by Django 5.1 on 2024-10-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0013_alter_candidateeducation_feild_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateskill",
            name="Description",
            field=models.TextField(default="Good"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Expert", "Expert"),
                ],
                default="Beginner ",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_description",
            field=models.TextField(),
        ),
    ]
