# Generated by Django 5.1 on 2024-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0014_candidateskill_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateskill",
            name="experience",
            field=models.CharField(
                choices=[
                    ("Fresher", "Fresher"),
                    ("1-2 Years", "1-2 Years"),
                    ("2-5 Years", "2-5 Years"),
                    ("5-10 Years", "5-10 Years"),
                    ("10+ Years", "10+ Years"),
                ],
                default="Fresher",
                max_length=50,
            ),
        ),
    ]
