# Generated by Django 5.1 on 2024-10-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0015_alter_candidateskill_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateskill",
            old_name="skill",
            new_name="skill_id",
        ),
    ]
