# Generated by Django 5.1 on 2024-10-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0017_remove_candidateskill_skill_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateskill",
            old_name="candidate",
            new_name="candidate_id",
        ),
    ]
