# Generated by Django 5.1 on 2024-10-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0018_rename_candidate_candidateskill_candidate_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateskill",
            old_name="candidate_id",
            new_name="candidate",
        ),
    ]
