# Generated by Django 5.1 on 2024-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0019_rename_candidate_id_candidateskill_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="region",
            field=models.CharField(default="India", max_length=50),
        ),
    ]
