# Generated by Django 5.1 on 2024-10-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0020_job_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="jobSkill",
            fields=[
                (
                    "skill_id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobwebsite.job"
                    ),
                ),
            ],
        ),
    ]
