# Generated by Django 5.1 on 2024-10-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0021_jobskill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="skills",
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(related_name="jobs", to="jobwebsite.jobskill"),
        ),
    ]
