# Generated by Django 5.1 on 2024-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0022_remove_job_skills_job_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
