# Generated by Django 5.1 on 2024-11-18 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0023_alter_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="interviews",
            name="interview_type",
            field=models.CharField(
                choices=[("HR Interview", "HR Interview"),
                         ("Technical", "Technical")],
                default="HR Interview",
                max_length=50,
            ),
        ),
    ]
