# Generated by Django 5.1 on 2024-11-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0025_alter_job_deadline"),
    ]

    operations = [
    ]
