# Generated by Django 5.1 on 2024-11-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0026_remove_jobskill_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobskill",
            name="job",
        ),
    ]
