# Generated by Django 5.1 on 2024-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobwebsite", "0027_remove_jobskill_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsapplication",
            name="resume",
            field=models.FileField(default="resume/resume.pdf", upload_to="resume/"),
        ),
    ]
